spring:
    active:
    - dev
---
spring: 
    profiles: dev #开发环境
    application:
        name: microservicecloud-config-dg-dev
---
spring:
    profiles: test #测试环境
    application:
        name: microservicecloud-config-dg-test
# 请保存问UTF-8格式